//
//  SearchInteractor.swift
//  itunesapi_cs
//
//  Created by Alejandro Melo Domínguez on 7/27/19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchBusinessLogic {
	func startSearch(term: String, page: Int)

    func nextPage(term: String, page: Int)
    func didSelectMedia(media: Media)
}

protocol SearchDataStore {
    var lastTerm: String { get set }
    var currentPage: Int { get set }
    var currentMedias: [Media] { get set }
    var selectedMedia: Media? { get set }
}

protocol SearchPresentationLogic: NSObject {
	func displayResults(medias:  [Media])
	func displayMediaDetails(media: Media)
	func displayLoadingIndicator()
	func dismissLoadingIndicator()
}

class SearchInteractor: SearchBusinessLogic, SearchDataStore {
    weak var presenter: SearchPresentationLogic? = nil
    var worker: SearchWorker? = SearchWorker()


    // MARK: - Data Store
    var lastTerm = ""
    var currentPage: Int = 1
    var currentMedias = [Media]()
    var selectedMedia: Media? = nil

    // MARK: - Business logic

    func startSearch(term: String, page: Int) {
		presenter?.displayLoadingIndicator()

		worker?.fetchMedia(for: term, page: page) { (success, medias) in
			self.presenter?.dismissLoadingIndicator()
			
			if success {
				self.currentMedias = medias
				let response = medias
				self.presenter?.displayResults(medias: response)
			} else {
				
			}
		
        }
    }

    func nextPage(term: String, page: Int) {
        guard term == lastTerm else {
            startSearch(term: term, page: 1)
            return
        }

        currentPage += 1
        lastTerm = term

        worker?.fetchMedia(for: term, page: currentPage) { (success, medias) in
			let filtered = medias.filter { $0.collectionId != nil && $0.kind != nil && $0.kind! == "song" }
			self.currentMedias.append(contentsOf: filtered)
			let response = self.currentMedias

			self.presenter?.displayResults(medias: response)
		}
		
    }

    func didSelectMedia(media: Media) {
        presenter?.displayMediaDetails(media: media)
    }
}
