//
//  SearchWorker.swift
//  itunesapi_cs
//
//  Created by Alejandro Melo Domínguez on 7/27/19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SearchWorker {
	let searchURL = URL(string: "https://itunes.apple.com/search?media=music")!
	let resultsPerPage = 20
	
	
    func fetchMedia(
        for term: String,
        page: Int,
        completion: @escaping ((_ success: Bool, _ medias: [Media]) -> Void)
    ) {
        let queryURL = searchURL(for: term, page: page)

        ApiClient.get(queryURL.absoluteString, success: { response in
            do {
                let searchNode = try JSONDecoder().decode(SearchNode.self, from: response)
                completion(true, searchNode.results)
            } catch {
                completion(false, [Media]())
            }
        }) { error in
            completion(false, [Media]())
        }
    }
}

extension SearchWorker {
    func searchURL(for term: String, page: Int = 1) -> URL {
        var urlComponents = URLComponents(url: searchURL, resolvingAgainstBaseURL: false)!

        guard var queryItems = urlComponents.queryItems else {
            let termItem = URLQueryItem(name: "term", value: term)
            let pageItem = URLQueryItem(name: "offset", value: String((page - 1) * resultsPerPage))

            urlComponents.queryItems = [termItem, pageItem]
            return urlComponents.url!
        }

        let termItem = URLQueryItem(name: "term", value: term)
        let pageItem = URLQueryItem(name: "offset", value: String((page - 1) * resultsPerPage))

        queryItems.append(contentsOf: [termItem, pageItem])
        urlComponents.queryItems = queryItems

        return urlComponents.url!
    }
}
